[tool.poetry]
name = "geedar-lib"
version = "0.1.0"
description = ""
authors = ["lucasuchoa98 <lucasuchoalg@gmail.com>"]
readme = "README.md"
packages = [{include = "geedar_lib"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
